### ISSUE TITLE
rows with in a row in mdDataTable

### ISSUE THREAD

**Issue by penumatsasiva** [iamisti/mdDataTable#100]
hii 
     From the last day i was trying to put the rows inside a row of material style like

       <mdt-table virtual-repeat="true">
    <mdt-header-row>
      <mdt-column align-rule="left">Dessert (100g serving)</mdt-column>
      <mdt-column align-rule="center">Calories</mdt-column>

    </mdt-header-row>
    
    <mdt-row ng-repeat="nutrition in nutritionList">
      <mdt-cell>{{nutrition.name}}</mdt-cell>
      <mdt-cell>{{nutrition.calories}}</mdt-cell>
      
      
         <mdt-row ng-repeat="nutrition1 in nutrition.data ">
       <mdt-cell>{{nutrition1.city}}</mdt-cell>   </mdt-row>
     
    </mdt-row>
  but nested ng-repeat is not working,can any body help me in this code plz
![Uploading mdtable.png…]()

**Comment by iamisti** [comment]
@penumatsasiva nested ng-repeat will not work. 
Please try to use `mdt-row` attribute instead of the element directive, to make sure you have more functions you can use.

With the conjuction of `mdt-row` attribute and using `mdt-custom-cell`, you will able to do that.
Please check the documentation to learn more how those works.
