### ISSUE TITLE
Dependency Injector Error

### ISSUE THREAD

**Issue by mgween** [iamisti/mdDataTable#113]
I get this error when I try to add the dependency to my code:

Uncaught Error: [$injector:modulerr] 

Normally I get this error when I make a mistake with linking the files, but they are definitely linked properly. I really hope that bower isn't required. I don't know how to use package managers. Is there a problem with including my files like this?

```
<link rel="stylesheet" href="mdDataTable-master/dist/md-data-table-style.css">

<script src="mdDataTable-master/dist/md-data-table.js"></script>

 <script src="mdDataTable-master/dist/md-data-table-templates.js"></script>
```

**Comment by iamisti** [comment]
Hi @mgween , thanks for raising this question.

First of all, your order is wrong, you have to load the `md-data-table-templates.js` and then the `md-data-table.js`. This should fix the issue.

On the other hand I'd not suggest to load the component through the url you provided.
The problems with your approach are:

- Your project will use the latest version of the component which is a problem if it has breaking changes. E.g.: your project will no longer work, due the braking changes. Since you are always referring to the latest release.

- Security. It's not a good idea to have 3rd party urls in your project.
  If you include Javascript or JSONP code from another domain, that code has full client-side power and can do whatever it wants.
  It can send AJAX requests to automatically make your user do things, and it can steal document.cookie.
  If your authentication cookies are HTTP-only, it can't steal them, but it can still impersonate the user using AJAX.

  Never include a JS file from a domain you don't trust.
  
  If your page uses SSL, all Javascript files must also use SSL, or an attacker can modify the un-encrypted Javascript to do whatever he wants. For this reason, browsers will show a security warning if an SSL page uses non-SSL resources.

  Note that JSONP is no exception to this rule. Any JSONP response has full access to your DOM. If security is a concern, do not use untrusted JSONP APIs.
[origin](http://stackoverflow.com/questions/5313290/when-linking-to-an-external-js-file-isnt-this-a-security-risk)

- Uptime: you can never know the uptime of the server where you server your 3rd party javascript data(library/component). The more 3rd party urls you use, the less stable your website will be.

So just try to dig in a bit into package-managers, it's really not that hard. If you have 1 hour to check it, you'll be surprised how easy the work with them.
