### ISSUE TITLE
Use comparison

### ISSUE THREAD

**Issue by JesusTheHun** [iamisti/mdDataTable#146]
Hello,

I've run into your implementation of a material data table and into this one : https://github.com/daniel-nagy/md-data-table .

Since he started to develop his version before yours, and I bet you were well aware of it, can you tell me what motivated you to develop a version of your own ? For what reason/case I should use your version over your (or opposite) ?

Thank you

**Comment by iamisti** [comment]
I'd recommend to read this:
http://stackoverflow.com/questions/27511487/is-there-a-table-component-in-angular-material

I didn't copy, we had the same idea, I guess he was copying mine after he saw mine. (probably he created his repo, I don't know, but I was for sure not copying him)

I prefer mine, since he put a lot of things which was not part of google material table design. I'm sticking to that design and trying to do it in the right way, excluding 100 different and useless feature as much as I can.
