### ISSUE TITLE
Bower distribution Issues

### ISSUE THREAD

**Issue by AndreeVela** [iamisti/mdDataTable#151]
Hi, I'm not capable to get the last version (currently the 1.6.8 according to the bower.json file) through bower. I think this is because the last version released is the 1.6.6. That version is not compatible with last version of angular material 1.1.0. Have you planned release the 1.6.8 version?

**Comment by iamisti** [comment]
@AndreeVela hello, you might saw the development bower.json file, which usually lives in the `master` branch or most likely on a separate `feature-` branch.
You can never get the version specified in the `master` or `feature-` branch, it needs to be released in order to do that.

Now `1.6.8` is released, you can use it.
