### ISSUE TITLE
search not work

### ISSUE THREAD

**Issue by elvis-macak** [iamisti/mdDataTable#197]
`http://codepen.io/elvismacak/pen/rrvEZN?editors=1000`

I forked your codepen, and the search feature can work  in 
```
  <mdt-table mdt-row="{'data': filteredItems,
                      'table-row-id-key': 'id',
                      'column-keys': ['name', 'calories', 'fat', 'carbs', 'protein', 'sodium', 'calcium', 'iron']}">
    <mdt-header-row>
...
```

but not in 
```
<mdt-row ng-repeat="nutrition in nutritionList">
```

you can try that in the codepen, just enter the search input, the duplicate content will be shown

**Comment by iamisti** [comment]
Hi @elvis-macak ,

Thanks for reporting the issue. I am aware of it.
The problem is with transclusion, `<mdt-row ng-repeat...` works with transclusion inside `mdt-table` and there are some limitation which makes it really hard (or even not possible) to workaround some cases, like this (dynamic content -> refresh the state of transcluded elements/recompile).

Because of this, `<mdt-row>` is already deprecated to use, although I haven't mark it as a deprecated element.
Please use `mdt-row` attribute always and your problem will be solved (as you noticed as well).
