### ISSUE TITLE
First row doesn't display the html cell content with 'mdt-custom-cell'

### ISSUE THREAD

**Issue by zweeen** [iamisti/mdDataTable#198]
Hi iamisti,

First of all, thx a lot for this great component :)

I have tried to use the **Custom cell content** with md-data-table. It's appears that some rows does'nt display the content of their **Custom cell content** instead of it shows the value of their cell.

Table attributes used : _virtual-repeat_ and _mdt-row_

I have also noticed  : 
          - every 13 rows this bug appears.
          - if virtual-repeat is set to false the bug doesn't appear.
          - when scrolling down till the first row disapear from the view and then scrolling up the bug doesn't appear on the fisrt row.

Here I made a [codepen](http://codepen.io/anon/pen/mAKJYq) to clarify you the issue 

best regards,

**Comment by iamisti** [comment]
Hi @zweeen !

Thank you for creating your ticket. 
The issue is unfortunately well known and it's not on our side, or not something we can fix at the moment. The issue is located in angular material with their virtual repeat directive.

See more here: https://github.com/angular/material/issues/9275

You can also give your vote to make it more important for them to fix! 👍

**Comment by zweeen** [comment]
Thx @iamisti, of course I will vote. Please keep us informed if they fix the bug :)

**Comment by iamisti** [comment]
update: I'm going to try a custom build they made us to fix this bug in the next days.

**Comment by zweeen** [comment]
Ok Thx @iamisti :)
