### ISSUE TITLE
Rows are not cleared if data updated

### ISSUE THREAD

**Issue by origami-z** [iamisti/mdDataTable#56]
Oops, it's me again. This is a strange one.

If the data for table rows are re-assigned, old rows are not deleted. Demo is available [here](http://codepen.io/zhc/pen/MKprGE) (note the change after 2 seconds).

I had a look at the code, it seems that `angular.js` did try to remove the old data/row (If you set a break point around Line 27530 (search the comment "remove leftover items"). I don't know why this is happening, as I saw `$scope.rowDataStorage = []` in `mdtRowDirective`. And I'm confused about why the pagination works when change the number per page choice.

**Comment by iamisti** [comment]
Hi there, no worries, I'm glad to help you out.
So there is a known issue with `mdt-row` element directives.
Try to use `mdt-row` attribute of the `mdt-table` and it'll just work.

Currently I don't have a solution for the element directive to fix, since it's a bigger problem with how transclusion is working. 

Is that enough for you to use `mdt-row` attribute? The only restrictions is that you can't use html content there at the moment.

**Comment by davidcui2** [comment]
It's fine for me. If it's a known issue, I'm happy that you close this one. :)

**Comment by iamisti** [comment]
Great, I'll try to fix that as soon as possible. I leave it open until I fix it. Thanks for the issue tho!

**Comment by roytz** [comment]
Hi,
I don't want to be rude but I was wondering if there's an excpected date for a release that contains this issue fix?

**Comment by iamisti** [comment]
Hi, nothing to worry about!
I can't tell you, since it's something I have to dig in, and until I don't know what causes the problem/how to solve it, I can't guarantee an exact date or release for it.
Currently try to use the `mdt-row` attribute, since it's provides everything you'd need.

**Comment by roytz** [comment]
But if I'll use mdt-row attribute I wouldn't be able to add buttons and other html elements to each row, right?
