### ISSUE TITLE
fire event whenever a row is selected/unselected

### ISSUE THREAD

**Issue by roytz** [iamisti/mdDataTable#64]
Is there an option to fire an event whenever a row is selected/unselected?
I tried ng-click on the mdt-row but it doesn't fire at all

**Comment by iamisti** [comment]
Not at the moment. But we can have it fairly easily.
But rather fireing an event, I'd vote to have the same approach as with the deleted rows. E.g.: calling a callback with the newly selected row/rows.

Do you need only that row what is recently selected, or it would be also fine to have the set of selected rows returned?

**Comment by roytz** [comment]
Thanks.
I need the set of the selected rows.
So you suggest I'll use the delete row callback?

**Comment by iamisti** [comment]
No, sorry if I wasn't clear.
That's a new feature. I'll put it in today, so from tomorrow you'll able to use it soon. More information about it later today. (most probably at night)

**Comment by roytz** [comment]
Oh ok.
Thank you!
One other thing, there's an open issue regarding deleted/modified rows that are being appended to the previous rows (for example, deleted rows are not being deleted from the table).
Will this issue also be taken care of soon?

**Comment by iamisti** [comment]
It's not part if this issue, but here is your answer:

This is a known issue when you using `mdt-row` directive explicitly. Unfortunately the issue is originating the way transclusion works and I don't have a nice workaround for it yet.
But!

It's already exist a workaround for that. Try to use this directive as an attribute for the `mdt-table`. You have to provide your data there and It will work well.

Example usage of `mdt-row` attribute: http://codepen.io/iamisti/pen/bEBKYx

**Comment by iamisti** [comment]
Selected rows callback feature added to `1.3.0` release.

**Comment by roytz** [comment]
Thank you
